# This is a basic workflow to help you get started with Actions

name: CI-CD-deploy

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [workflow_dispatch]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  deploy:
    name: deploy app
    # The type of runner that the job will run on
    runs-on: [ self-hosted ]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    # Runs a single command using the runners shell
    - name: run deploy script
      run: /home/pi/actions-runner/scripts/deploy.sh


